PUT http://localhost:80/api/lists/
Content-Type: application/json

{
  "name": "myList"
}

###
PUT http://localhost:80/api/lists/f6b0e056-7bed-480a-a9b4-d2b7a049e854/items
Content-Type: application/json

{
   "name": "Картошка"
}

###
GET http://localhost:80/api/lists/f6b0e056-7bed-480a-a9b4-d2b7a049e854
Content-Type: application/json